#! /bin/bash

COMMAND='0,/\[\[update\]\]/{s/\[\[update\]\]/\[\[update\]\]\ncontent\ =\ "'"$1"'"\ntimestamp\ =\ '"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'\n\n\[\[update\]\]/}'
echo "$COMMAND"
sed -i "$COMMAND" priv/Config.toml